# Generated by Django 2.1 on 2018-08-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=75)),
                ('brand_slug', models.CharField(blank=True, editable=False, max_length=75)),
            ],
        ),
    ]
