# Generated by Django 2.1 on 2018-08-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_model', models.CharField(max_length=100)),
                ('phone_model_slug', models.CharField(blank=True, editable=False, max_length=100)),
                ('phone_image', models.ImageField(upload_to='uploads/images')),
                ('description', models.TextField(blank=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mprices.Brand')),
            ],
        ),
    ]
