# Generated by Django 2.1 on 2018-08-21 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0004_auto_20180820_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='release',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
