# Generated by Django 2.1 on 2018-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0005_phone_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
