# Generated by Django 2.1 on 2018-08-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0006_phone_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
        migrations.AddField(
            model_name='phone',
            name='audio',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='phone',
            name='battery',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='phone',
            name='builtin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='card',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='chipset',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='colors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='cpu',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='phone',
            name='data',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='phone',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='extra',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='phone',
            name='extra_display',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='features',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='phone',
            name='front_camera',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='phone',
            name='games',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='gg_band',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='phone',
            name='ggg_band',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='gggg_band',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='phone',
            name='gps',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='phone',
            name='gpu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='main_camera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='messaging',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='nfc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='phone',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='phone',
            name='protection',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='sensors',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='phone',
            name='sim',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='phone',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='technology',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='torch',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='phone',
            name='usb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='weight',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='phone',
            name='wlan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_model',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
