# Generated by Django 2.1 on 2018-08-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0007_auto_20180823_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='data',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='games',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='gg_band',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='ggg_band',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='gggg_band',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='messaging',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='nfc',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='sim',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='torch',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='usb',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='wlan',
        ),
    ]
