# Generated by Django 2.1 on 2018-08-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0009_auto_20180823_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phone_video',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
