# Generated by Django 2.1 on 2018-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0010_phone_phone_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Coming Soon', 'Coming Soon')], default='Available', max_length=12),
        ),
    ]
