# Generated by Django 2.1 on 2018-08-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0011_phone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='gsm_arena',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
