# Generated by Django 2.1 on 2018-08-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0013_auto_20180829_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='cpu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='phone',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
