# Generated by Django 2.1 on 2018-08-29 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0014_auto_20180829_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
