# Generated by Django 2.1 on 2018-09-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0016_auto_20180829_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-release', '-price']},
        ),
        migrations.AddField(
            model_name='phone',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_image',
            field=models.ImageField(blank=True, upload_to='uploads/images'),
        ),
    ]
