# Generated by Django 2.1 on 2018-09-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0017_auto_20180910_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
