# Generated by Django 2.1 on 2018-09-15 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0019_remove_phone_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
