# Generated by Django 2.1 on 2018-09-28 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0020_auto_20180915_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
