# Generated by Django 2.1 on 2018-10-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0022_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='country',
            name='exchage_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
