# Generated by Django 2.1 on 2018-10-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0024_auto_20181005_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='exchage_rate',
            new_name='exchange_rate',
        ),
    ]
