# Generated by Django 2.1 on 2018-10-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0026_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
