# Generated by Django 2.1 on 2018-10-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0027_auto_20181006_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12),
        ),
    ]
