# Generated by Django 2.1 on 2018-11-28 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mprices', '0028_auto_20181006_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name'], 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name'], 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-release', '-price'], 'verbose_name_plural': 'Phones'},
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='mprices.Country'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='mprices.Brand'),
        ),
    ]
